"use client";
import { useLayoutEffect, useMemo, useRef, useState, type MouseEvent } from "react";
import { getCourse } from "@/lib/course-data";
import { AI_LAB_MISSIONS, advanceAiLabMission, advanceAiLabStep, buildAiLabDeck, chooseAiLabAction, createAiLabState } from "@/lib/ai-verification-lab";
import "./AiVerificationLab.css";
interface AiVerificationLabProps { completedCourseIds: string[]; onStartCourse: (courseId: string) => void }
const REQUIRED_COURSE_IDS = ["email-message", "online-collaboration", "ai-helper", "verify-ai", "digital-project"] as const;
const MODE_ICONS = { email: "✉", collab: "◎", prompt: "AI", verify: "⌕", project: "▤", report: "✓" } as const;
export function AiVerificationLab({ completedCourseIds, onStartCourse }: AiVerificationLabProps) {
  const completedRequired = REQUIRED_COURSE_IDS.filter((id) => completedCourseIds.includes(id)); const unlocked = completedRequired.length === REQUIRED_COURSE_IDS.length;
  const nextCourse = getCourse(REQUIRED_COURSE_IDS.find((id) => !completedCourseIds.includes(id)) ?? ""); const [mode, setMode] = useState<"menu" | "lab">("menu"); const [rotation, setRotation] = useState(0);
  const deck = useMemo(() => buildAiLabDeck(rotation), [rotation]); const [game, setGame] = useState(() => createAiLabState(AI_LAB_MISSIONS.length)); const headingRef = useRef<HTMLHeadingElement>(null); const shouldFocusRef = useRef(false);
  useLayoutEffect(() => { if (!shouldFocusRef.current) return; headingRef.current?.focus(); shouldFocusRef.current = false; }, [game.index, game.stepIndex, game.phase, mode]);
  function focusNext() { shouldFocusRef.current = true; } function startLab() { focusNext(); setGame(createAiLabState(deck.length)); setMode("lab"); }
  function replayLab() { const nextRotation = rotation + 1; focusNext(); setRotation(nextRotation); setGame(createAiLabState(buildAiLabDeck(nextRotation).length)); }
  if (!unlocked) return <section className="ai-lab-shell ai-lab-locked" id="ai-verification-lab" aria-labelledby="ai-lab-heading"><span className="ai-lab-mascot" aria-hidden="true">🔬</span><div><p className="section-kicker">离线示例 · 证据优先</p><h2 id="ai-lab-heading">AI 核验研究站</h2><p>先完成未来协作站五课，再来练习邮件、协作、AI 提问、核验和项目交付。</p><strong>已完成 {completedRequired.length} / {REQUIRED_COURSE_IDS.length} 门必修课</strong></div>{nextCourse ? <button onClick={() => onStartCourse(nextCourse.id)} type="button">下一门：{nextCourse.title}</button> : null}</section>;
  if (mode === "menu") return <section className="ai-lab-shell ai-lab-menu" id="ai-verification-lab" aria-labelledby="ai-lab-heading"><div><p className="section-kicker">不盲信 · 会拆分 · 找证据</p><h2 id="ai-lab-heading" ref={headingRef} tabIndex={-1}>AI 核验研究站</h2><p>完成六项虚拟研究任务，分清工具建议、资料证据和自己的最终判断。</p></div><div className="ai-lab-missions" aria-label="六项研究任务" role="list">{AI_LAB_MISSIONS.map((mission) => <span key={mission.id} role="listitem"><b aria-hidden="true">{MODE_ICONS[mission.mode]}</b><i>{mission.title}</i><small>{mission.skill}</small></span>)}</div><button className="ai-lab-action" onClick={startLab} type="button">领取六项研究任务 <span aria-hidden="true">→</span></button></section>;
  if (game.phase === "complete") return <section className="ai-lab-shell ai-lab-complete" id="ai-verification-lab" aria-labelledby="ai-lab-complete-heading"><span aria-hidden="true">🧪</span><div><p>六项虚拟研究全部完成</p><h2 id="ai-lab-complete-heading" ref={headingRef} tabIndex={-1}>核验证据链完成！</h2><small>你会清楚沟通、合理分工，也知道 AI 的答案必须经过资料核对。</small></div><ul aria-label="已经掌握的未来协作能力">{["收件人、主题与清楚正文", "角色、权限与版本", "目标、背景与隐私边界", "拆事实、找来源与标不确定", "任务分解、依赖与预览", "人类决定、工具建议与证据"].map((skill) => <li key={skill}>✓ {skill}</li>)}</ul><div><button className="ai-lab-action" onClick={replayLab} type="button">重做六项研究</button><button className="ai-lab-action ai-lab-action--quiet" onClick={() => { focusNext(); setMode("menu"); }} type="button">返回研究站入口</button></div></section>;
  const mission = deck[game.index]; const step = mission.steps[game.stepIndex];
  function choose(event: MouseEvent<HTMLButtonElement>, actionId: string) { setGame((current) => chooseAiLabAction(current, mission, actionId, event.detail)); }
  function nextStep(event: MouseEvent<HTMLButtonElement>) { focusNext(); setGame((current) => advanceAiLabStep(current, mission, event.detail)); }
  function nextMission(event: MouseEvent<HTMLButtonElement>) { focusNext(); setGame((current) => advanceAiLabMission(current, event.detail)); }
  return <section className={`ai-lab-shell ai-lab-game lab-${mission.mode}`} id="ai-verification-lab" aria-labelledby="ai-lab-mission-heading"><button className="ai-lab-back" onClick={() => { focusNext(); setMode("menu"); }} type="button">← 返回研究站入口</button><header className="ai-lab-heading"><span aria-hidden="true">{MODE_ICONS[mission.mode]}</span><div><p>研究 {game.index + 1} / {deck.length} · {mission.skill}</p><h2 id="ai-lab-mission-heading" ref={headingRef} tabIndex={-1}>{mission.title}</h2><small>{mission.story}</small></div><progress aria-label="AI 核验六项研究进度" max={deck.length} value={game.solved} /></header><div className="ai-lab-layout"><section className="ai-lab-workbench" aria-labelledby="ai-lab-step-heading"><span className="ai-lab-step-count">核验步骤 {game.stepIndex + 1} / {mission.steps.length}</span><h3 id="ai-lab-step-heading">{step.prompt}</h3><div className="ai-lab-signals" aria-label="当前虚构信息与证据" role="list">{step.signals.map((labSignal) => <article aria-current={labSignal.state === "active" ? "step" : undefined} className={`ai-lab-signal is-${labSignal.state ?? "normal"}`} key={labSignal.id} role="listitem"><span aria-hidden="true">{labSignal.state === "warning" ? "!" : MODE_ICONS[mission.mode]}</span><b>{labSignal.label}</b><small>{labSignal.detail}</small></article>)}</div><div className="ai-lab-actions" aria-label="选择研究行动" role="group">{step.options.map((candidate) => <button aria-pressed={game.phase !== "investigating" && candidate.id === step.answerId} className="ai-lab-action" disabled={game.phase !== "investigating"} key={candidate.id} onClick={(event) => choose(event, candidate.id)} type="button">{candidate.label}</button>)}</div><p className={`ai-lab-feedback phase-${game.phase}`} role="status">{game.feedback}</p>{game.phase === "step-solved" ? <button className="ai-lab-action ai-lab-next" onClick={nextStep} type="button">保存证据，继续核验 →</button> : null}{game.phase === "mission-solved" ? <button className="ai-lab-action ai-lab-next" onClick={nextMission} type="button">{game.index === deck.length - 1 ? "查看研究总结" : "接收下一项研究"} <span aria-hidden="true">→</span></button> : null}</section><aside className="ai-lab-evidence" aria-labelledby="ai-lab-evidence-heading"><div><span aria-hidden="true">⌕</span><h3 id="ai-lab-evidence-heading">核验证据记录</h3></div>{game.evidence.length > 0 ? <ol>{game.evidence.map((evidence, index) => <li key={`${mission.id}-${index}`}><span>{index + 1}</span>{evidence}</li>)}</ol> : <p>完成第一步后，这里会记录可复述的核验理由。</p>}<small>所有邮件、AI 输出和协作对象都是虚构示例，不连接真实服务。</small></aside></div></section>;
}
