export type AiLabMode = "email" | "collab" | "prompt" | "verify" | "project" | "report";
export type AiLabPhase = "investigating" | "step-solved" | "mission-solved" | "complete";
export interface AiLabSignal { id: string; label: string; detail: string; state?: "normal" | "active" | "checked" | "warning" }
export interface AiLabStep { prompt: string; signals: AiLabSignal[]; options: Array<{ id: string; label: string }>; answerId: string; explanation: string; evidence: string; wrongFeedback: string }
export interface AiLabMission { id: string; title: string; story: string; skill: string; courseId: string; mode: AiLabMode; steps: AiLabStep[] }
export interface AiLabState { index: number; missionCount: number; stepIndex: number; solved: number; phase: AiLabPhase; evidence: string[]; feedback: string }
const option = (id: string, label: string) => ({ id, label });
const signal = (id: string, label: string, detail: string, state: AiLabSignal["state"] = "normal"): AiLabSignal => ({ id, label, detail, state });

export const AI_LAB_MISSIONS: AiLabMission[] = [
  { id: "email-launch", title: "邮件发射台", story: "检查一封不会真实发送的虚构班级邮件。", skill: "收件人、主题与清楚正文", courseId: "email-message", mode: "email", steps: [
    { prompt: "发送示例邮件前，第一轮要核对什么？", signals: [signal("to", "收件人", "科学小队", "active"), signal("subject", "主题", "周五观星安排", "checked"), signal("body", "正文", "时间、地点、任务")], options: [option("check", "核对收件人、主题和正文目标"), option("rush", "不预览直接发送"), option("secret", "加入私人联系方式")], answerId: "check", explanation: "先核对对象和目的，能避免发错人或让主题含糊。", evidence: "邮件：对象、主题、目的相互一致", wrongFeedback: "观察邮件的三块信息，先确认它要发给谁、为了什么。" },
    { prompt: "正文提到观察表附件，怎样避免遗漏？", signals: [signal("sentence", "正文", "请查看观察表", "checked"), signal("attachment", "附件区", "目前为空", "warning"), signal("preview", "发送前预览", "待完成", "active")], options: [option("attach", "添加示例附件并再次预览"), option("ignore", "正文说有就算完成"), option("unknown", "随便附一个文件")], answerId: "attach", explanation: "正文与附件区要相互印证，预览能发现遗漏。", evidence: "邮件：正文提到附件时核对附件区", wrongFeedback: "比较正文承诺与附件区的实际状态。" },
  ] },
  { id: "collab-console", title: "协作控制台", story: "为虚构班级项目安排在线协作。", skill: "角色、权限与版本", courseId: "online-collaboration", mode: "collab", steps: [
    { prompt: "三个人一起做海报，哪种分工最清楚？", signals: [signal("writer", "文字员", "整理说明", "active"), signal("artist", "画面员", "制作图标"), signal("checker", "核对员", "检查来源")], options: [option("roles", "每人负责一块，并约定交接时间"), option("all", "所有人同时改所有内容"), option("none", "不说明谁负责什么")], answerId: "roles", explanation: "明确角色和交接点能减少重复和遗漏。", evidence: "协作：角色清楚，交接可见", wrongFeedback: "想想如果两个人同时改同一句话，会发生什么。" },
    { prompt: "只需要同伴评论时，应给什么权限？", signals: [signal("owner", "项目负责人", "可编辑", "checked"), signal("peer", "试读同伴", "需要反馈", "active"), signal("public", "公开链接", "未开启", "checked")], options: [option("comment", "只给评论权限"), option("edit", "给所有人完全编辑"), option("public", "公开给任何人")], answerId: "comment", explanation: "按任务给最少需要的权限，能保护作品并保留反馈。", evidence: "协作：权限与任务匹配", wrongFeedback: "同伴只需要留下建议，不需要改动原文。" },
  ] },
  { id: "prompt-cabin", title: "AI 提问舱", story: "向一个离线示例 AI 提出虚构学习任务。", skill: "目标、背景与隐私边界", courseId: "ai-helper", mode: "prompt", steps: [
    { prompt: "哪种提示更容易得到有用的学习建议？", signals: [signal("goal", "目标", "解释水循环", "active"), signal("audience", "对象", "二年级学生"), signal("format", "格式", "三步加一个例子")], options: [option("structured", "说明目标、对象和输出格式"), option("vague", "只说“帮我”"), option("personal", "附上真实姓名和学校")], answerId: "structured", explanation: "具体目标、背景和格式能帮助工具理解任务，不需要个人资料。", evidence: "AI 提问：具体任务，不给个人资料", wrongFeedback: "有用的提示需要任务信息，而不是孩子的身份信息。" },
    { prompt: "示例 AI 给出答案后，下一步是什么？", signals: [signal("answer", "AI 建议", "水变成云是凝结", "active"), signal("warning", "工具提醒", "可能出错", "warning"), signal("source", "课程资料", "有水循环图")], options: [option("verify", "对照课程资料再使用"), option("trust", "看到完整句子就直接相信"), option("share", "马上转发给所有人")], answerId: "verify", explanation: "AI 输出是待检查的建议，不是自动正确的事实。", evidence: "AI 使用：输出先核验再采用", wrongFeedback: "流畅的句子也可能出错，找一份独立资料比较。" },
  ] },
  { id: "verification-desk", title: "AI 核验台", story: "核对一段虚构 AI 给出的动物说明。", skill: "拆事实、找来源与标不确定", courseId: "verify-ai", mode: "verify", steps: [
    { prompt: "AI 说“海豚是鱼而且用鳃呼吸”，先怎么检查？", signals: [signal("claim-a", "事实 1", "海豚是鱼", "warning"), signal("claim-b", "事实 2", "用鳃呼吸", "warning"), signal("source", "科普资料", "哺乳动物、用肺", "active")], options: [option("split", "拆成两条事实并逐条找来源"), option("style", "只检查语句是否好听"), option("majority", "重复问 AI 三次就算证据")], answerId: "split", explanation: "拆分主张再逐条核对，能定位具体错误。", evidence: "核验：把答案拆成可检查的事实", wrongFeedback: "一个句子里可能有多条主张，需要分别检查。" },
    { prompt: "两份可靠资料一致、AI 答案不同，应怎样记录？", signals: [signal("book", "资料 A", "海豚是哺乳动物", "checked"), signal("museum", "资料 B", "海豚用肺呼吸", "checked"), signal("ai", "AI 输出", "与资料冲突", "warning")], options: [option("correct", "采用资料结论并标出 AI 错误"), option("hide", "删掉核验过程"), option("average", "把两种说法拼在一起")], answerId: "correct", explanation: "用可追溯资料纠正错误，并保留核验说明。", evidence: "核验：交叉来源一致，标记工具错误", wrongFeedback: "证据冲突时，不要把真假说法平均在一起。" },
  ] },
  { id: "project-board", title: "数字项目看板", story: "安排一份虚构班级数字展览。", skill: "任务分解、依赖与预览", courseId: "digital-project", mode: "project", steps: [
    { prompt: "制作展览页面时，哪种顺序最合理？", signals: [signal("plan", "确定目标", "先做", "active"), signal("assets", "准备内容", "依赖目标"), signal("build", "制作与核对", "依赖内容")], options: [option("order", "目标 → 内容 → 制作 → 核对"), option("publish", "发布 → 再决定目标"), option("random", "每个人随便开始")], answerId: "order", explanation: "按依赖拆任务，前一步的结果成为下一步输入。", evidence: "项目：按依赖拆分可交付任务", wrongFeedback: "哪些事情必须先完成，后面的工作才有依据？" },
    { prompt: "发布前最后一轮应检查什么？", signals: [signal("links", "按钮", "示例链接可用", "checked"), signal("credits", "来源", "说明完整", "checked"), signal("preview", "小屏预览", "待检查", "active")], options: [option("preview", "检查内容、来源、按钮和不同屏幕"), option("looks", "只看封面颜色"), option("identity", "添加同学联系方式")], answerId: "preview", explanation: "发布检查要覆盖内容、交互、来源和观众设备。", evidence: "项目：发布前完整预览", wrongFeedback: "数字项目不仅是图片，还包括内容、按钮和不同屏幕。" },
  ] },
  { id: "research-report", title: "综合研究报告", story: "完成一份虚构比特岛研究报告。", skill: "人类决定、工具建议与证据", courseId: "verify-ai", mode: "report", steps: [
    { prompt: "报告中怎样说明 AI 的参与最清楚？", signals: [signal("human", "小队决定", "研究问题与结论", "checked"), signal("ai", "工具建议", "提供提纲草案", "active"), signal("evidence", "资料证据", "核验结论")], options: [option("roles", "区分人类决定、AI 建议和资料证据"), option("claim", "把 AI 内容都当成自己发现"), option("delegate", "让 AI 决定最终结论")], answerId: "roles", explanation: "标明各自角色，能看出谁做决定、什么被核验。", evidence: "报告：人类负责目标、判断与结论", wrongFeedback: "工具可以建议，但研究问题和最终判断由谁负责？" },
    { prompt: "遇到仍无法确认的示例数据，应怎样发布？", signals: [signal("claim", "待确认数据", "只有一个来源", "warning"), signal("note", "不确定说明", "尚未添加", "active"), signal("report", "报告", "准备交付")], options: [option("uncertain", "标为待确认，暂不写成事实"), option("guess", "选一个听起来像真的数字"), option("remove-source", "隐藏来源不足")], answerId: "uncertain", explanation: "诚实标记不确定，比编造确定答案更可靠。", evidence: "报告：证据不足就标记待确认", wrongFeedback: "不知道不是失败，想想怎样诚实表达证据边界。" },
  ] },
];

export function buildAiLabDeck(rotation: number): AiLabMission[] { const r = Number.isFinite(rotation) ? Math.max(0, Math.floor(rotation)) : 0; const o = AI_LAB_MISSIONS.length ? r % AI_LAB_MISSIONS.length : 0; return [...AI_LAB_MISSIONS.slice(o), ...AI_LAB_MISSIONS.slice(0, o)]; }
export function createAiLabState(missionCount: number): AiLabState { const count = Number.isFinite(missionCount) ? Math.max(0, Math.floor(missionCount)) : 0; return { index: 0, missionCount: count, stepIndex: 0, solved: 0, phase: count ? "investigating" : "complete", evidence: [], feedback: "观察虚构信息和证据，再选择下一步。" }; }
export function chooseAiLabAction(state: AiLabState, mission: AiLabMission, actionId: string, detail = 1): AiLabState { if (detail > 1 || state.phase !== "investigating") return state; const step = mission.steps[state.stepIndex]; if (!step || !step.options.some((candidate) => candidate.id === actionId)) return state; if (actionId !== step.answerId) return { ...state, feedback: step.wrongFeedback }; return { ...state, phase: state.stepIndex === mission.steps.length - 1 ? "mission-solved" : "step-solved", evidence: [...state.evidence, step.evidence], feedback: step.explanation }; }
export function advanceAiLabStep(state: AiLabState, mission: AiLabMission, detail = 1): AiLabState { if (detail > 1 || state.phase !== "step-solved" || state.stepIndex >= mission.steps.length - 1) return state; return { ...state, stepIndex: state.stepIndex + 1, phase: "investigating", feedback: "证据已写入研究记录，继续核对下一步。" }; }
export function advanceAiLabMission(state: AiLabState, detail = 1): AiLabState { if (detail > 1 || state.phase !== "mission-solved") return state; const solved = Math.min(state.missionCount, state.solved + 1); if (state.index >= state.missionCount - 1) return { ...state, solved, phase: "complete", feedback: "六项研究与核验任务全部完成。" }; return { ...state, index: state.index + 1, stepIndex: 0, solved, phase: "investigating", evidence: [], feedback: "新研究任务已打开，先观察虚构信息。" }; }
