export interface CodingCard { id: string; code: string; prompt: string; options: [string, string, string]; answer: string; explanation: string; }
export interface CodingMission { courseId: string; courseName: string; badgeId: string; stages: [string, string, string, string, string, string]; messages: [string, string, string, string, string, string]; cards: [CodingCard, CodingCard, CodingCard, CodingCard]; }
const card = (id: string, code: string, prompt: string, options: [string, string, string], answer: string, explanation: string): CodingCard => ({ id, code, prompt, options, answer, explanation });
export const CODING_MISSIONS: Record<string, CodingMission> = {
  "events-handlers": { courseId: "events-handlers", courseName: "事件启动器", badgeId: "event-controller", stages: ["程序等待事件", "事件来自哪里", "处理器来响应", "多个事件", "事件顺序", "事件追踪挑战"], messages: ["事件是程序能注意到的事情，例如按键、点击或计时结束。", "用户、传感器和系统都可能产生事件。", "事件处理器规定事件发生时运行哪些指令。", "一个角色可以响应不同事件，同一事件也能通知多个部分。", "程序按事件实际发生的时间响应，不能假设用户一定先做哪一步。", "追踪四段事件程序会产生什么结果。"], cards: [card("e1", "当按下空格键 → 跳跃", "还没有按键时角色会？", ["等待", "一直跳", "退出"], "等待", "事件驱动程序会等待匹配事件。"), card("e2", "当点击星星 → 分数增加1", "点击两次后分数增加多少？", ["2", "1", "0"], "2", "每次点击事件都运行一次处理器。"), card("e3", "当计时结束 → 显示完成", "什么触发显示完成？", ["计时结束事件", "鼠标移动", "文件名"], "计时结束事件", "处理器只响应它监听的事件。"), card("e4", "当按左键→向左；当按右键→向右", "先右后左，最后一次动作是？", ["向左", "向右", "不动"], "向左", "事件按实际发生顺序分别运行。") ] },
  "variables-score": { courseId: "variables-score", courseName: "变量能量箱", badgeId: "variable-keeper", stages: ["变量保存会变化的值", "名称说明用途", "读取当前值", "更新旧值", "初始值很重要", "变量追踪挑战"], messages: ["变量像带名字的盒子，保存程序运行时会变化的数据。", "score 比 x 更能说明盒子装的是分数。", "读取变量会得到它此刻保存的值。", "score = score + 1 会先读旧值、计算、再存回新值。", "程序开始时要设置清楚的初始值。", "用纸笔追踪四个小程序中的变量。"], cards: [card("v1", "分数=0；分数=分数+1", "最后分数？", ["1", "0", "2"], "1", "从0开始加1并存回变量。"), card("v2", "生命=3；生命=生命-1", "最后生命？", ["2", "3", "1"], "2", "读取3、减1，再把2存回。"), card("v3", "名字='比比'；显示名字", "屏幕显示？", ["比比", "名字", "0"], "比比", "读取变量得到其中保存的文字。"), card("v4", "星星=1；星星=星星+2；星星=星星+1", "最后星星？", ["4", "3", "2"], "4", "变量每次更新都基于当时的当前值。") ] },
  "functions-tools": { courseId: "functions-tools", courseName: "函数工具箱", badgeId: "function-builder", stages: ["给一组指令命名", "调用才会运行", "参数带来变化", "返回一个结果", "复用减少重复", "函数调用挑战"], messages: ["函数把一组有意义的指令装进有名字的工具。", "定义函数是在制作工具，调用函数才真正使用它。", "参数把本次调用需要的不同信息传进去。", "有些函数完成动作，有些会返回计算结果。", "复用同一函数能减少重复，也让修改集中在一处。", "判断四个函数定义和调用。"], cards: [card("f1", "定义 问好()：显示'你好'；调用 问好()", "会显示？", ["你好", "什么都不显示", "问好"], "你好", "调用会执行函数中的指令。"), card("f2", "定义 前进(格数)；调用 前进(3)", "参数3表示？", ["本次前进3格", "调用3次文件", "变量消失"], "本次前进3格", "参数为这次调用提供具体值。"), card("f3", "定义 加倍(数)：返回 数×2；结果=加倍(4)", "结果？", ["8", "4", "2"], "8", "函数用参数4计算并返回8。"), card("f4", "三处都要画同一颗星", "更容易维护的方法？", ["定义画星函数并调用三次", "复制后分别乱改", "删除两处"], "定义画星函数并调用三次", "复用让共同逻辑只需在一处修改。") ] },
  "boolean-logic": { courseId: "boolean-logic", courseName: "真假逻辑门", badgeId: "logic-gate-keeper", stages: ["真假两种结果", "并且两个都要真", "或者至少一个真", "不是会翻转", "组合条件加括号", "逻辑门挑战"], messages: ["布尔值只有真和假，常用于决定是否行动。", "A并且B只有两边都为真时才是真。", "A或者B只要至少一边为真就是真。", "不是会把真变假、把假变真。", "组合多个条件时用括号写清先判断哪部分。", "打开四座真假逻辑门。"], cards: [card("b1", "有钥匙=true；门关闭=true", "有钥匙 并且 门关闭？", ["真", "假", "不确定"], "真", "并且两边都是真，所以结果为真。"), card("b2", "下雨=false；下雪=true", "下雨 或者 下雪？", ["真", "假", "数字"], "真", "或者只需至少一个条件为真。"), card("b3", "危险=false", "不是 危险？", ["真", "假", "0"], "真", "不是会翻转真假。"), card("b4", "有票=true；有大人=false", "有票 并且 有大人？", ["假", "真", "两次"], "假", "并且要求两个条件同时为真。") ] },
  "game-design": { courseId: "game-design", courseName: "小游戏设计总装", badgeId: "game-designer", stages: ["目标和规则", "输入与事件", "变量记录状态", "循环更新世界", "测试平衡与安全", "小游戏设计挑战"], messages: ["游戏先需要清楚目标、规则和结束条件。", "按键、点击等事件把玩家选择送进程序。", "分数、生命和位置等变量记录游戏状态。", "游戏循环反复读取输入、更新状态并画出画面。", "请别人试玩，用证据调整难度；不收集不必要的个人信息。", "为一款虚拟收星游戏完成四个设计决定。"], cards: [card("g1", "目标：收集5颗星", "哪个变量最需要？", ["已收集星星数", "真实住址", "壁纸颜色"], "已收集星星数", "变量记录达成目标所需的变化状态。"), card("g2", "按方向键移动角色", "这使用了什么？", ["键盘事件处理器", "文件扩展名", "邮件附件"], "键盘事件处理器", "按键事件触发对应移动指令。"), card("g3", "如果碰到星星", "合适的后续规则？", ["分数加1并移走这颗星", "公开密码", "无限复制窗口"], "分数加1并移走这颗星", "条件检测碰撞后更新分数和世界状态。"), card("g4", "试玩者总在10秒内失败", "下一步？", ["记录原因并一次调整一处再测", "责怪试玩者", "删除所有规则"], "记录原因并一次调整一处再测", "小步调整和复测能找到更合适的平衡。") ] },
};
export interface CodingState { index: number; solved: number; completed: boolean; feedback: { kind: "idle" | "retry" | "correct"; message: string }; }
export const createCodingState = (): CodingState => ({ index: 0, solved: 0, completed: false, feedback: { kind: "idle", message: "先用手指追踪代码，再选择结果。" } });
export function answerCodingCard(mission: CodingMission, state: CodingState, optionIndex: number): CodingState {
  if (state.completed) return state;
  const current = mission.cards[state.index];
  if (!current || current.options[optionIndex] !== current.answer) return { ...state, feedback: { kind: "retry", message: `再追踪一次：${current?.explanation ?? "从第一行开始。"}` } };
  const completed = state.index === mission.cards.length - 1;
  return { index: completed ? state.index : state.index + 1, solved: state.solved + 1, completed, feedback: { kind: "correct", message: completed ? "四段代码全部追踪成功！" : current.explanation } };
}
