import type{RelayMission,RelaySignal}from"./decision-relay.ts";const o=(id:string,label:string)=>({id,label});const s=(id:string,label:string,detail:string,state:RelaySignal["state"]="normal"):RelaySignal=>({id,label,detail,state});
export const COMPUTER_PILOT_MISSIONS:RelayMission[]=[
{id:"keyboard-route",title:"键盘航线",story:"驾驶虚拟飞船完成方向和快捷键任务。",skill:"方向键、确认与快捷键",courseId:"keyboard-flight",mode:"keyboard",steps:[{prompt:"光标要从 A 点移到右边两格，应怎样操作？",signals:[s("start","A 点","第 1 列","active"),s("target","目标","第 3 列","ready"),s("keys","方向键","← ↑ ↓ →")],options:[o("right","按两次 →"),o("left","按两次 ←"),o("enter","只按 Enter")],answerId:"right",explanation:"方向键按屏幕坐标移动，向右两格需要两次右箭头。",evidence:"键盘：方向与次数匹配目标",wrongFeedback:"比较起点和目标的列位置。"},{prompt:"选中虚拟按钮后，怎样用键盘确认？",signals:[s("focus","按钮焦点","边框已亮","active"),s("enter","Enter","确认"),s("escape","Esc","取消")],options:[o("confirm","按 Enter 确认"),o("arrows","继续按方向键不确认"),o("random","同时按很多键")],answerId:"confirm",explanation:"焦点表示当前对象，Enter 执行确认。",evidence:"键盘：先定位焦点，再确认",wrongFeedback:"观察哪一个键被标为确认。"}]},
{id:"mouse-control",title:"鼠标控制",story:"在虚拟控制台完成指向、单击、双击和拖动。",skill:"指向、点击与拖放",courseId:"mouse-precision",mode:"mouse",steps:[{prompt:"选择一个按钮但不打开文件，应该怎样做？",signals:[s("pointer","指针","已经对准按钮","active"),s("single","单击","选择一次"),s("double","双击","常用于打开")],options:[o("single","稳定单击一次"),o("double","快速双击"),o("drag","拖走按钮")],answerId:"single",explanation:"单击用于选择或按按钮，双击不是所有任务都需要。",evidence:"鼠标：操作次数匹配任务",wrongFeedback:"题目只要求选择，不要求打开。"},{prompt:"把虚拟图标送进目标框，完整动作是什么？",signals:[s("icon","图标","起点","active"),s("bay","目标框","右侧","ready"),s("button","鼠标左键","持续按住")],options:[o("drag","按住 → 移动 → 到框内松开"),o("click","只点一下起点"),o("release","先松开再移动")],answerId:"drag",explanation:"拖放要从按住开始，在目标内松开结束。",evidence:"鼠标：拖放包含按住、移动、松开",wrongFeedback:"拖动过程中哪一步让图标跟着指针移动？"}]},
{id:"input-switch",title:"输入切换",story:"在示例卡片里输入中英文和数字。",skill:"大小写、数字与输入法",courseId:"bilingual-input",mode:"input",steps:[{prompt:"要输入大写 A，哪种操作提供真实大小写证据？",signals:[s("target","目标","A","active"),s("shift","Shift","临时大写"),s("a","字母键","a")],options:[o("uppercase","按住 Shift 再按 A"),o("lowercase","只按 a"),o("caps","输入数字 1")],answerId:"uppercase",explanation:"Shift 与字母组合产生一次大写输入。",evidence:"输入：修饰键与字符键配合",wrongFeedback:"目标是大写，不是小写或数字。"},{prompt:"拼音还在组合时，什么时候确认汉字？",signals:[s("pinyin","拼音组合","xue xi","active"),s("candidate","候选词","学习","ready"),s("confirm","确认","Enter 或空格")],options:[o("composition","选对候选词后确认"),o("early","组合未完成就提交"),o("english","切成英文并忽略候选")],answerId:"composition",explanation:"输入法先组合拼音，选择正确候选后才形成汉字。",evidence:"输入：完成组合并核对候选",wrongFeedback:"屏幕上仍显示拼音时，汉字还没有最终确认。"}]},
{id:"desktop-captain",title:"桌面船长",story:"管理一张虚拟桌面上的窗口和任务栏。",skill:"窗口、焦点与任务栏",courseId:"desktop-adventure",mode:"desktop",steps:[{prompt:"两个窗口重叠时，怎样把记事本放到前面？",signals:[s("notes","记事本","后方"),s("paint","画图","前方","active"),s("taskbar","任务栏","两个应用")],options:[o("focus","单击记事本窗口或任务栏图标"),o("close-all","关闭所有窗口"),o("restart","重启虚拟桌面")],answerId:"focus",explanation:"单击窗口或任务栏图标可改变当前焦点。",evidence:"桌面：一个窗口获得当前焦点",wrongFeedback:"任务只要求切换前后，不需要关闭内容。"},{prompt:"暂时收起窗口但稍后继续，应选择什么？",signals:[s("work","未完成文档","仍需保留","active"),s("minimize","最小化","收到任务栏"),s("close","关闭","可能结束任务")],options:[o("minimize","最小化到任务栏"),o("close","直接关闭"),o("delete","删除虚拟文档")],answerId:"minimize",explanation:"最小化保留窗口状态，任务栏可以再次恢复。",evidence:"桌面：最小化与关闭作用不同",wrongFeedback:"“稍后继续”需要保留哪个状态？"}]},
{id:"program-launch",title:"程序启停",story:"从虚拟应用列表安全启动并结束一个程序。",skill:"程序图标、启动与退出",courseId:"program-landing",mode:"program",steps:[{prompt:"怎样确认打开的是目标画图程序？",signals:[s("icon","画图图标","调色板","active"),s("name","应用名称","比特画板"),s("other","其他程序","音乐播放器")],options:[o("identity","核对图标和名称后单击启动"),o("guess","随便打开一个"),o("many","同时打开全部程序")],answerId:"identity",explanation:"图标和名称共同帮助识别程序。",evidence:"程序：启动前核对应用身份",wrongFeedback:"不要只凭位置猜，观察图标旁的应用名称。"},{prompt:"作品已经保存，怎样正常结束程序？",signals:[s("saved","保存状态","已保存","ready"),s("window","程序窗口","仍打开","active"),s("close","关闭按钮","右上角")],options:[o("exit","使用关闭按钮退出"),o("power","强行关闭虚拟电脑"),o("delete","删除应用")],answerId:"exit",explanation:"保存后通过窗口关闭按钮正常退出程序。",evidence:"程序：先确认保存，再正常退出",wrongFeedback:"结束一个程序不需要关闭整台电脑或删除应用。"}]},
{id:"pilot-test",title:"驾驶考试",story:"完成一条虚拟电脑操作综合航线。",skill:"观察、操作与状态确认",courseId:"desktop-adventure",mode:"flight",steps:[{prompt:"按顺序完成“打开画板并把窗口最小化”，哪条路线正确？",signals:[s("app","画板图标","桌面"),s("window","画板窗口","打开后出现"),s("taskbar","任务栏","最小化后保留","active")],options:[o("route","核对图标 → 单击启动 → 最小化"),o("reverse","先最小化 → 再找图标"),o("delete","删除图标 → 关闭桌面")],answerId:"route",explanation:"每一步产生下一步所需的可见状态。",evidence:"综合：按依赖顺序完成操作",wrongFeedback:"窗口出现之前，不能先最小化它。"},{prompt:"怎样证明整个任务完成而不是只凭感觉？",signals:[s("app","画板","任务栏中","ready"),s("desktop","桌面","窗口已收起","ready"),s("evidence","状态证据","两处相互印证","active")],options:[o("verify","核对任务栏图标与桌面状态"),o("memory","只说“我好像做过”"),o("repeat","不停重复点击")],answerId:"verify",explanation:"读取屏幕状态能证明程序仍在、窗口已最小化。",evidence:"综合：用可见状态验证结果",wrongFeedback:"找出哪两处屏幕信息能共同证明任务完成。"}]}
];
