export type CreativeProjectMode = "pixel" | "document" | "slides" | "copyright" | "table" | "showcase";
export type CreativeStudioPhase = "drafting" | "step-solved" | "project-solved" | "complete";
export interface CreativeCanvasCard { id: string; label: string; detail: string; state?: "normal" | "active" | "ready" }
export interface CreativeProjectStep { prompt: string; canvas: CreativeCanvasCard[]; options: Array<{ id: string; label: string }>; answerId: string; explanation: string; evidence: string; wrongFeedback: string }
export interface CreativeStudioProject { id: string; title: string; story: string; skill: string; courseId: string; mode: CreativeProjectMode; steps: CreativeProjectStep[] }
export interface CreativeStudioState { index: number; projectCount: number; stepIndex: number; solved: number; phase: CreativeStudioPhase; portfolio: string[]; feedback: string }

const option = (id: string, label: string) => ({ id, label });
const card = (id: string, label: string, detail: string, state: CreativeCanvasCard["state"] = "normal"): CreativeCanvasCard => ({ id, label, detail, state });

export const CREATIVE_STUDIO_PROJECTS: CreativeStudioProject[] = [
  { id: "pixel-blueprint", title: "像素图纸", story: "为比特岛制作一枚虚构火箭徽章。", skill: "网格与有限色板", courseId: "pixel-art", mode: "pixel", steps: [
    { prompt: "开始画小图标时，哪种方法最容易看清轮廓？", canvas: [card("grid", "8 × 8 网格", "每格一个像素", "active"), card("rocket", "火箭轮廓", "左右大致对称"), card("palette", "色板", "蓝、黄、白")], options: [option("outline", "先用一种颜色搭轮廓"), option("random", "每格随机换颜色"), option("tiny", "不用网格画极细线")], answerId: "outline", explanation: "先搭清楚轮廓，能在小网格中检查形状和对称。", evidence: "像素图：先轮廓，后细节", wrongFeedback: "观察画布尺寸很小，先想什么最影响远处辨认。" },
    { prompt: "怎样让火箭在小尺寸下仍然清楚？", canvas: [card("blue", "深蓝", "背景", "ready"), card("yellow", "亮黄", "火焰", "active"), card("white", "白色", "船身", "ready")], options: [option("contrast", "限制三色并拉开明暗"), option("many", "加入二十种近似颜色"), option("same", "背景和火箭用同一颜色")], answerId: "contrast", explanation: "少量且对比清楚的颜色，让像素图缩小后仍可辨认。", evidence: "色板：少而有对比", wrongFeedback: "比较背景和主体是否容易分开，颜色不是越多越好。" },
  ] },
  { id: "document-editor", title: "文档编辑", story: "整理一份虚构班级观星说明。", skill: "标题、正文与留白", courseId: "document-design", mode: "document", steps: [
    { prompt: "哪种排版能让读者先看懂主题？", canvas: [card("title", "观星小队", "主标题", "active"), card("intro", "周五观察月亮", "正文"), card("tips", "带上记录板", "提示")], options: [option("hierarchy", "标题最大，正文统一，提示突出"), option("all-big", "所有文字一样大"), option("rainbow", "每个字换一种字体")], answerId: "hierarchy", explanation: "明确层级让眼睛按标题、正文、提示的顺序阅读。", evidence: "文档：标题建立阅读层级", wrongFeedback: "想一想读者第一眼应该先看到哪一段。" },
    { prompt: "内容挤在一起时，怎样提高可读性？", canvas: [card("block-a", "观察时间", "第一段", "ready"), card("space", "段间留白", "呼吸区", "active"), card("block-b", "安全提醒", "第二段", "ready")], options: [option("spacing", "增加段间留白并左对齐"), option("compress", "缩小到一行塞满"), option("scatter", "把文字任意散开")], answerId: "spacing", explanation: "稳定对齐和适当留白能把相关内容分组。", evidence: "文档：对齐与留白帮助分组", wrongFeedback: "观察两段内容的边界，读者需要看出哪里换了一组。" },
  ] },
  { id: "slide-director", title: "幻灯片导演", story: "为班级安排一段虚构机器人救援故事。", skill: "故事顺序与单页重点", courseId: "slide-story", mode: "slides", steps: [
    { prompt: "四页故事怎样排序最连贯？", canvas: [card("begin", "1 出发", "认识任务", "active"), card("find", "2 发现故障", "出现问题"), card("solve", "3 合作修复", "解决问题"), card("end", "4 安全回家", "结果")], options: [option("story", "出发 → 故障 → 修复 → 回家"), option("reverse", "回家 → 修复 → 出发 → 故障"), option("shuffle", "每次随机排列")], answerId: "story", explanation: "开头、问题、解决和结果形成读者能跟上的故事线。", evidence: "幻灯片：一页推动一步故事", wrongFeedback: "先找开头和结果，再看中间的问题如何被解决。" },
    { prompt: "第二页文字太多，怎样让观众听你讲？", canvas: [card("image", "故障机器人图", "主要画面", "ready"), card("headline", "桥梁传感器失灵", "一句重点", "active"), card("paragraph", "八行说明", "待精简")], options: [option("one-idea", "保留一幅图和一句重点"), option("paste", "把整篇文档贴上去"), option("effects", "给每个字加不同动画")], answerId: "one-idea", explanation: "一页一个重点，画面辅助讲述，不替代讲述。", evidence: "幻灯片：一页一个重点", wrongFeedback: "观众需要同时看屏幕和听讲，哪种信息量更合适？" },
  ] },
  { id: "copyright-check", title: "素材版权员", story: "为比特岛虚构海报选择可以使用的素材。", skill: "许可、来源与再创作", courseId: "media-copyright", mode: "copyright", steps: [
    { prompt: "哪张图片最适合安全加入作品？", canvas: [card("self", "自己画的星球", "作者：小队", "active"), card("licensed", "允许使用的火箭", "许可说明清楚"), card("unknown", "来源不明的图片", "没有作者信息")], options: [option("known", "选择自制或许可清楚的素材"), option("unknown", "复制来源不明的图片"), option("crop", "裁掉水印就能使用")], answerId: "known", explanation: "自制或许可清楚的素材最容易确认使用边界。", evidence: "版权：先确认作者和许可", wrongFeedback: "观察每张素材是否能回答“谁做的、允许怎么用”。" },
    { prompt: "使用允许转载的虚构火箭图后，还要做什么？", canvas: [card("work", "火箭图", "许可：可用于学习", "ready"), card("credit", "来源说明", "作者与许可", "active"), card("poster", "班级海报", "待发布")], options: [option("credit", "在作品旁写来源与许可"), option("claim", "写成全部由自己创作"), option("hide", "把来源藏起来")], answerId: "credit", explanation: "留下作者和许可说明，尊重创作者也方便以后核对。", evidence: "版权：作品旁保留来源说明", wrongFeedback: "允许使用不等于变成自己的作品，想想怎样说明贡献。" },
  ] },
  { id: "data-table", title: "数据表设计师", story: "整理一份虚构班级植物观察表。", skill: "表头、数据类型与合计", courseId: "data-table", mode: "table", steps: [
    { prompt: "怎样设计表格才能比较每天的高度？", canvas: [card("date", "日期", "文字", "ready"), card("height", "高度（厘米）", "数字", "active"), card("note", "观察", "文字", "ready")], options: [option("columns", "每列一种数据，单位写在表头"), option("mix", "日期和高度混在同一格"), option("decorate", "用合并单元格画图案")], answerId: "columns", explanation: "稳定的列和表头单位让每行记录可以比较。", evidence: "表格：一列一种数据，单位进表头", wrongFeedback: "想一想同一列里的内容是否能用同一种方式比较。" },
    { prompt: "要知道三天一共长高多少，应该选择什么计算？", canvas: [card("day1", "第 1 天", "2 厘米"), card("day2", "第 2 天", "1 厘米"), card("day3", "第 3 天", "3 厘米", "active")], options: [option("sum", "合计 2 + 1 + 3 = 6"), option("count", "只数有 3 行"), option("guess", "看颜色猜答案")], answerId: "sum", explanation: "问题问总量，所以把同一单位的三次增长相加。", evidence: "表格：根据问题选择合计", wrongFeedback: "先读问题里的“一共”，再判断要数行还是加数值。" },
  ] },
  { id: "showcase-publish", title: "综合发布台", story: "把五项成果组合成一份虚构班级比特岛展览。", skill: "项目检查与观众视角", courseId: "pixel-art", mode: "showcase", steps: [
    { prompt: "发布前最完整的检查顺序是哪一组？", canvas: [card("content", "内容", "准确清楚", "ready"), card("rights", "素材", "许可与来源", "ready"), card("data", "表格", "单位和计算", "active")], options: [option("checklist", "内容 → 排版 → 素材 → 数据"), option("looks", "只看颜色好不好看"), option("rush", "不预览直接发布")], answerId: "checklist", explanation: "综合检查覆盖作品表达、使用边界和数据证据。", evidence: "发布：用清单逐项检查", wrongFeedback: "作品不只要好看，还要准确、可读并尊重素材来源。" },
    { prompt: "给低年级同学观看时，最后应该怎样调整？", canvas: [card("audience", "观众", "低年级同学", "active"), card("preview", "预览", "字大、步骤短", "ready"), card("project", "展览", "准备完成")], options: [option("audience", "放大重点并请同伴试读"), option("jargon", "加入更多难词显得专业"), option("personal", "加入同学真实联系方式")], answerId: "audience", explanation: "根据观众试读反馈调整，作品才能真正传达信息。", evidence: "发布：按观众试读结果改进", wrongFeedback: "想一想观众能不能看清、看懂，以及哪些信息不该出现。" },
  ] },
];

export function buildCreativeProjectDeck(rotation: number): CreativeStudioProject[] { const r = Number.isFinite(rotation) ? Math.max(0, Math.floor(rotation)) : 0; const offset = CREATIVE_STUDIO_PROJECTS.length ? r % CREATIVE_STUDIO_PROJECTS.length : 0; return [...CREATIVE_STUDIO_PROJECTS.slice(offset), ...CREATIVE_STUDIO_PROJECTS.slice(0, offset)]; }
export function createCreativeStudioState(projectCount: number): CreativeStudioState { const count = Number.isFinite(projectCount) ? Math.max(0, Math.floor(projectCount)) : 0; return { index: 0, projectCount: count, stepIndex: 0, solved: 0, phase: count ? "drafting" : "complete", portfolio: [], feedback: "观察画布、读清目标，再做一个设计决定。" }; }
export function chooseCreativeDecision(state: CreativeStudioState, project: CreativeStudioProject, decisionId: string, detail = 1): CreativeStudioState { if (detail > 1 || state.phase !== "drafting") return state; const step = project.steps[state.stepIndex]; if (!step || !step.options.some((candidate) => candidate.id === decisionId)) return state; if (decisionId !== step.answerId) return { ...state, feedback: step.wrongFeedback }; return { ...state, phase: state.stepIndex === project.steps.length - 1 ? "project-solved" : "step-solved", portfolio: [...state.portfolio, step.evidence], feedback: step.explanation }; }
export function advanceCreativeStep(state: CreativeStudioState, project: CreativeStudioProject, detail = 1): CreativeStudioState { if (detail > 1 || state.phase !== "step-solved" || state.stepIndex >= project.steps.length - 1) return state; return { ...state, stepIndex: state.stepIndex + 1, phase: "drafting", feedback: "设计理由已放入作品集，继续完成下一步。" }; }
export function advanceCreativeProject(state: CreativeStudioState, detail = 1): CreativeStudioState { if (detail > 1 || state.phase !== "project-solved") return state; const solved = Math.min(state.projectCount, state.solved + 1); if (state.index >= state.projectCount - 1) return { ...state, solved, phase: "complete", feedback: "六个创作项目全部完成。" }; return { ...state, index: state.index + 1, stepIndex: 0, solved, phase: "drafting", portfolio: [], feedback: "新项目画布已打开，先观察作品目标。" }; }
