export type RelayPhase = "active" | "step-solved" | "mission-solved" | "complete";
export interface RelaySignal { id: string; label: string; detail: string; state?: "normal" | "active" | "ready" | "warning" }
export interface RelayStep { prompt: string; signals: RelaySignal[]; options: Array<{ id: string; label: string }>; answerId: string; explanation: string; evidence: string; wrongFeedback: string }
export interface RelayMission { id: string; title: string; story: string; skill: string; courseId: string; mode: string; steps: RelayStep[] }
export interface RelayState { index: number; missionCount: number; stepIndex: number; solved: number; phase: RelayPhase; evidence: string[]; feedback: string }
export function buildRelayDeck<T extends RelayMission>(missions: readonly T[], rotation: number): T[] { const r = Number.isFinite(rotation) ? Math.max(0, Math.floor(rotation)) : 0; const offset = missions.length ? r % missions.length : 0; return [...missions.slice(offset), ...missions.slice(0, offset)]; }
export function createRelayState(missionCount: number): RelayState { const count = Number.isFinite(missionCount) ? Math.max(0, Math.floor(missionCount)) : 0; return { index: 0, missionCount: count, stepIndex: 0, solved: 0, phase: count ? "active" : "complete", evidence: [], feedback: "观察信号和目标，再选择下一步。" }; }
export function chooseRelayAction(state: RelayState, mission: RelayMission, actionId: string, detail = 1): RelayState { if (detail > 1 || state.phase !== "active") return state; const step = mission.steps[state.stepIndex]; if (!step || !step.options.some((option) => option.id === actionId)) return state; if (actionId !== step.answerId) return { ...state, feedback: step.wrongFeedback }; return { ...state, phase: state.stepIndex === mission.steps.length - 1 ? "mission-solved" : "step-solved", evidence: [...state.evidence, step.evidence], feedback: step.explanation }; }
export function advanceRelayStep(state: RelayState, mission: RelayMission, detail = 1): RelayState { if (detail > 1 || state.phase !== "step-solved" || state.stepIndex >= mission.steps.length - 1) return state; return { ...state, stepIndex: state.stepIndex + 1, phase: "active", feedback: "证据已保存，继续完成下一步。" }; }
export function advanceRelayMission(state: RelayState, detail = 1): RelayState { if (detail > 1 || state.phase !== "mission-solved") return state; const solved = Math.min(state.missionCount, state.solved + 1); if (state.index >= state.missionCount - 1) return { ...state, solved, phase: "complete", feedback: "全部接力任务完成。" }; return { ...state, index: state.index + 1, stepIndex: 0, solved, phase: "active", evidence: [], feedback: "新任务已打开，先观察现场信号。" }; }
export function estimateRelayMinutesRemaining(missions: readonly RelayMission[], state: RelayState, totalMinutes = 9): number { if (!missions.length || state.phase === "complete") return 0; const totalSteps = missions.reduce((sum, mission) => sum + mission.steps.length, 0); if (!totalSteps) return 0; const completedMissions = missions.slice(0, state.index).reduce((sum, mission) => sum + mission.steps.length, 0); const currentProgress = Math.min(missions[state.index]?.steps.length ?? 0, state.stepIndex + (state.phase === "active" ? 0 : 1)); const remainingSteps = Math.max(0, totalSteps - completedMissions - currentProgress); const safeTotalMinutes = Number.isFinite(totalMinutes) ? Math.max(1, totalMinutes) : 9; return remainingSteps ? Math.max(1, Math.ceil(safeTotalMinutes * remainingSteps / totalSteps)) : 1; }
