export type FileRescueMode = "path" | "name" | "move" | "copy" | "type" | "restore";
export type FileRescuePhase = "rescuing" | "step-solved" | "mission-solved" | "complete";
export type VirtualFileState = "normal" | "active" | "done" | "trashed";
export interface VirtualFileCard { id: string; name: string; location: string; kind: "file" | "folder"; state?: VirtualFileState }
export interface FileRescueStep { prompt: string; files: VirtualFileCard[]; options: Array<{ id: string; label: string }>; answerId: string; explanation: string; evidence: string; wrongFeedback: string }
export interface FileRescueMission { id: string; title: string; story: string; skill: string; courseId: string; mode: FileRescueMode; steps: FileRescueStep[] }
export interface FileRescueState { index: number; missionCount: number; stepIndex: number; solved: number; phase: FileRescuePhase; evidence: string[]; feedback: string }
const option = (id: string, label: string) => ({ id, label });
const file = (id: string, name: string, location: string, kind: "file" | "folder", state: VirtualFileState = "normal"): VirtualFileCard => ({ id, name, location, kind, state });

export const FILE_RESCUE_MISSIONS: FileRescueMission[] = [
  { id: "path-finder", title: "路径寻路", story: "在虚构学习盘里按文件夹路径找到火箭实验记录。", skill: "文件与文件夹路径", courseId: "file-home", mode: "path", steps: [
    { prompt: "从根目录出发，先进入哪个文件夹？", files: [file("study", "学习", "/", "folder", "active"), file("pictures", "图片", "/", "folder"), file("games", "游戏", "/", "folder")], options: [option("open-study", "打开 /学习"), option("open-pictures", "打开 /图片"), option("open-file", "把文件夹当文件打开")], answerId: "open-study", explanation: "目标路径以 /学习 开头，所以先进入学习文件夹。", evidence: "路径第 1 段：/学习", wrongFeedback: "观察目标路径的第一段文件夹名称。" },
    { prompt: "来到 /学习，怎样找到目标？", files: [file("science", "科学", "/学习", "folder", "active"), file("math", "数学", "/学习", "folder"), file("target", "火箭实验.txt", "/学习/科学", "file", "active")], options: [option("science-target", "打开 科学/火箭实验.txt"), option("math", "进入数学"), option("root", "回根目录并猜")], answerId: "science-target", explanation: "文件完整位置是 /学习/科学/火箭实验.txt。", evidence: "完整路径：/学习/科学/火箭实验.txt", wrongFeedback: "观察文件卡标出的完整路径和当前文件夹。" },
  ] },
  { id: "clear-name", title: "清楚命名", story: "一张虚构火箭图片还叫“新建文件9.png”，需要清楚名称并保留类型尾巴。", skill: "文件命名与扩展名", courseId: "name-your-work", mode: "name", steps: [
    { prompt: "哪种新名称更清楚且保留图片扩展名？", files: [file("draft", "新建文件9.png", "/作品", "file", "active"), file("text", "火箭说明.txt", "/作品", "file")], options: [option("rename-good", "春游火箭.png"), option("rename-no-ext", "春游火箭"), option("rename-vague", "新建文件10.png")], answerId: "rename-good", explanation: "描述性名称便于查找，同时保留 .png 表示图片类型。", evidence: "新建文件9.png → 春游火箭.png", wrongFeedback: "观察名称是否说明内容，以及 .png 扩展名是否保留。" },
    { prompt: "文件夹里已经有同名文件，怎样避免覆盖？", files: [file("existing", "春游火箭.png", "/作品", "file", "done"), file("new", "春游火箭.png", "待保存", "file", "active")], options: [option("unique", "保存为 春游火箭-2.png"), option("overwrite", "不检查直接覆盖"), option("remove-ext", "删掉扩展名")], answerId: "unique", explanation: "使用清楚的序号产生唯一名称，并保留原文件。", evidence: "避免重名：春游火箭-2.png", wrongFeedback: "观察同一文件夹里已有同名文件，名称必须唯一且保留扩展名。" },
  ] },
  { id: "move-home", title: "移动归位", story: "虚构下载区的星球照片应该搬到图片文件夹。", skill: "移动原件", courseId: "move-and-copy", mode: "move", steps: [
    { prompt: "只改变原件位置，应该选择什么操作？", files: [file("photo", "星球照片.png", "/下载", "file", "active"), file("pictures", "图片", "/", "folder", "active")], options: [option("move", "移动到 /图片"), option("copy", "复制到 /图片"), option("rename", "只改名字")], answerId: "move", explanation: "移动会把同一份原件从下载区转到图片文件夹。", evidence: "移动：/下载 → /图片，仍为 1 份", wrongFeedback: "观察任务要求只保留一份并改变路径，注意文件数量。" },
    { prompt: "移动完成后，哪种状态才正确？", files: [file("old", "星球照片.png", "/下载（已移出）", "file", "done"), file("new", "星球照片.png", "/图片", "file", "active")], options: [option("one-copy", "/下载 0 份，/图片 1 份"), option("two", "两个位置各 1 份"), option("lost", "两个位置都没有")], answerId: "one-copy", explanation: "移动后原位置不再有文件，新位置保留唯一原件。", evidence: "移动验证：原位置 0 + 新位置 1", wrongFeedback: "观察移动前后路径与文件数量，移动不会产生第二份。" },
  ] },
  { id: "copy-backup", title: "复制备份", story: "数学练习要在原文件保留的同时，增加一份虚拟备份。", skill: "复制与数量", courseId: "move-and-copy", mode: "copy", steps: [
    { prompt: "怎样让原文件和备份都存在？", files: [file("homework", "数学练习.txt", "/学习/数学", "file", "active"), file("backup", "备份", "/", "folder", "active")], options: [option("copy", "复制到 /备份"), option("move", "移动到 /备份"), option("trash", "放进回收站")], answerId: "copy", explanation: "复制保留原件，并在目标路径产生一份独立副本。", evidence: "复制：原件保留 + /备份新增副本", wrongFeedback: "观察任务需要两个位置各有一份，注意数量证据。" },
    { prompt: "复制完成后，正确数量是多少？", files: [file("original", "数学练习.txt", "/学习/数学", "file", "done"), file("backup-copy", "数学练习.txt", "/备份", "file", "active")], options: [option("two", "总计 2 份"), option("one", "总计 1 份"), option("three", "总计 3 份")], answerId: "two", explanation: "一个原件加一个副本，总计两份。", evidence: "复制验证：2 个路径、2 份文件", wrongFeedback: "观察原路径和备份路径各有一张文件卡，数一数数量。" },
  ] },
  { id: "type-sorter", title: "类型分拣", story: "依据扩展名线索把虚构文件送进图片、文字与声音托盘。", skill: "文件类型", courseId: "file-types", mode: "type", steps: [
    { prompt: "三份文件分别应该进入哪个托盘？", files: [file("image", "星图.png", "待分类 · 图片线索", "file", "active"), file("text", "观察.txt", "待分类 · 文字线索", "file", "active"), file("sound", "鸟鸣.wav", "待分类 · 声音线索", "file", "active")], options: [option("sort-right", ".png→图片，.txt→文字，.wav→声音"), option("all-image", "全部放图片"), option("by-size", "只按文件名长短分类")], answerId: "sort-right", explanation: "扩展名为文件类型提供线索，可用于初步分类。", evidence: ".png 图片 · .txt 文字 · .wav 声音", wrongFeedback: "观察每个文件名末尾的扩展名线索。" },
    { prompt: "遇到陌生的 神秘.xyz，安全做法是什么？", files: [file("unknown", "神秘.xyz", "未知类型", "file", "active"), file("known", "说明.txt", "已知文字", "file", "done")], options: [option("ask", "先不打开，告诉可信大人"), option("open", "反复双击尝试"), option("rename", "改成 .png 就当图片")], answerId: "ask", explanation: "陌生扩展名只是未知线索，不能靠改名字变安全，应先求助。", evidence: "未知类型：不打开，先求助", wrongFeedback: "扩展名不能证明安全，陌生类型先停止并告诉可信大人。" },
  ] },
  { id: "trash-restore", title: "回收站恢复", story: "虚构数学图表被误放进回收站，救援队要恢复并确认路径。", skill: "恢复与搜索", courseId: "learning-backpack", mode: "restore", steps: [
    { prompt: "怎样安全找回误删文件？", files: [file("chart", "乘法图表.png", "/回收站", "file", "trashed"), file("math", "数学", "/学习", "folder", "active")], options: [option("restore", "从回收站恢复到 /学习/数学"), option("empty", "清空回收站"), option("recreate", "不查看就重新做")], answerId: "restore", explanation: "回收站允许恢复误删文件，不必重新创建或永久删除。", evidence: "恢复：/回收站 → /学习/数学", wrongFeedback: "观察文件仍在虚拟回收站，可以使用可逆的恢复操作。" },
    { prompt: "恢复后怎样确认真的找回了？", files: [file("restored", "乘法图表.png", "/学习/数学", "file", "active"), file("trash", "回收站", "该文件已不在", "folder", "done")], options: [option("verify", "搜索名称并核对完整路径"), option("guess", "只凭记忆说完成"), option("delete-again", "再次放回回收站")], answerId: "verify", explanation: "搜索名称并读取路径，能证明文件已经回到正确文件夹。", evidence: "搜索命中：/学习/数学/乘法图表.png", wrongFeedback: "救援完成需要可见证据，核对文件名和完整路径。" },
  ] },
];

export function buildFileRescueDeck(rotation: number): FileRescueMission[] { const r = Number.isFinite(rotation) ? Math.max(0, Math.floor(rotation)) : 0; const o = FILE_RESCUE_MISSIONS.length ? r % FILE_RESCUE_MISSIONS.length : 0; return [...FILE_RESCUE_MISSIONS.slice(o), ...FILE_RESCUE_MISSIONS.slice(0, o)]; }
export function createFileRescueState(missionCount: number): FileRescueState { const count = Number.isFinite(missionCount) ? Math.max(0, Math.floor(missionCount)) : 0; return { index: 0, missionCount: count, stepIndex: 0, solved: 0, phase: count ? "rescuing" : "complete", evidence: [], feedback: "观察文件名、路径和数量，再选择操作。" }; }
export function chooseFileAction(state: FileRescueState, mission: FileRescueMission, actionId: string, detail = 1): FileRescueState { if (detail > 1 || state.phase !== "rescuing") return state; const step = mission.steps[state.stepIndex]; if (!step || !step.options.some((o) => o.id === actionId)) return state; if (actionId !== step.answerId) return { ...state, feedback: step.wrongFeedback }; return { ...state, phase: state.stepIndex === mission.steps.length - 1 ? "mission-solved" : "step-solved", evidence: [...state.evidence, step.evidence], feedback: step.explanation }; }
export function advanceFileStep(state: FileRescueState, mission: FileRescueMission, detail = 1): FileRescueState { if (detail > 1 || state.phase !== "step-solved" || state.stepIndex >= mission.steps.length - 1) return state; return { ...state, stepIndex: state.stepIndex + 1, phase: "rescuing", feedback: "救援记录已保存，继续检查下一步。" }; }
export function advanceFileMission(state: FileRescueState, detail = 1): FileRescueState { if (detail > 1 || state.phase !== "mission-solved") return state; const solved = Math.min(state.missionCount, state.solved + 1); if (state.index >= state.missionCount - 1) return { ...state, solved, phase: "complete", feedback: "六次文件救援全部完成。" }; return { ...state, index: state.index + 1, stepIndex: 0, solved, phase: "rescuing", evidence: [], feedback: "新救援任务已打开，先观察虚拟文件。" }; }
