import type{RelayMission,RelaySignal}from"./decision-relay.ts";const o=(id:string,label:string)=>({id,label});const s=(id:string,label:string,detail:string,state:RelaySignal["state"]="normal"):RelaySignal=>({id,label,detail,state});
export const ISLAND_CHAMPIONSHIP_MISSIONS:RelayMission[]=[
{id:"launch-cup",title:"启航操作杯",story:"用屏幕状态证明一次虚拟操作完成。",skill:"输入与状态验证",courseId:"keyboard-flight",mode:"launch-harbor",steps:[{prompt:"打开画板并暂时收起，哪条证据链正确？",signals:[s("icon","画板图标","名称已核对"),s("window","窗口","曾经打开"),s("taskbar","任务栏","图标仍在","active")],options:[o("route","启动后最小化，并核对任务栏"),o("delete","删除图标"),o("guess","只凭感觉说完成")],answerId:"route",explanation:"先执行依赖顺序，再用任务栏状态核对结果。",evidence:"启航港：操作顺序与状态证据一致",wrongFeedback:"“暂时收起”需要保留哪个可见状态？"}]},
{id:"file-cup",title:"文件路径杯",story:"把模拟作品送到正确文件夹并保留副本。",skill:"路径、移动与复制",courseId:"file-home",mode:"file-forest",steps:[{prompt:"原件留在作品夹，备份放入学习包，应选择什么？",signals:[s("source","作品夹","星球图原件","active"),s("target","学习包","需要副本","ready"),s("path","目标路径","学习包 / 图片")],options:[o("copy","复制后核对两个路径"),o("move","只移动原件"),o("rename","只改名字")],answerId:"copy",explanation:"复制保留原件，并在目标路径产生副本。",evidence:"文件森林：动作效果与两个路径状态相符",wrongFeedback:"题目要求原位置仍有什么？"}]},
{id:"robot-cup",title:"机器人调试杯",story:"从固定轨迹找出第一处程序错误。",skill:"顺序、条件与调试",courseId:"bug-catcher",mode:"robot-workshop",steps:[{prompt:"机器人应右转避墙，却在检测到墙后前进，先改哪里？",signals:[s("condition","条件","前方有墙","ready"),s("action","当前动作","前进","warning"),s("trace","轨迹","撞在第 3 步","active")],options:[o("fix","把条件分支动作改为右转并复测"),o("random","重写全部程序"),o("ignore","忽略第 3 步证据")],answerId:"fix",explanation:"稳定复现后只改第一处不符合条件的动作，再用相同输入复测。",evidence:"机器人车间：轨迹定位错误并单点修复",wrongFeedback:"哪条证据最早偏离预期？"}]},
{id:"safety-cup",title:"安全判断杯",story:"面对虚构弹窗做出可解释的安全响应。",skill:"停止、核对与求助",courseId:"popup-fog",mode:"safety-lighthouse",steps:[{prompt:"弹窗要求立即填写姓名领取奖励，最佳行动是什么？",signals:[s("urgency","催促","只剩 5 秒","warning"),s("request","索取内容","姓名","warning"),s("adult","可信大人","可以求助","ready")],options:[o("safe","不填写、不点击，告诉可信大人"),o("submit","立即填写"),o("share","转给同学尝试")],answerId:"safe",explanation:"催促和索取个人信息都是停下核对的证据。",evidence:"安全灯塔：风险证据对应停止与求助",wrongFeedback:"哪个选择不会扩大风险？"}]},
{id:"hardware-cup",title:"硬件系统杯",story:"沿虚拟电脑的数据流找出故障位置。",skill:"输入、处理、存储与输出",courseId:"troubleshoot-machine",mode:"hardware-lab",steps:[{prompt:"键盘事件正常、CPU 结果正确，但屏幕无变化，先检查哪一段？",signals:[s("input","输入","事件已到","ready"),s("process","处理","结果 7","ready"),s("output","输出","屏幕未更新","warning")],options:[o("output","检查处理结果到输出设备的连接"),o("keyboard","拆掉正常键盘"),o("all","同时更换所有部件")],answerId:"output",explanation:"前两段已有正常证据，最小范围是输出链路。",evidence:"硬件岛：沿数据流缩小故障范围",wrongFeedback:"哪一段是第一处没有正常状态的地方？"}]},
{id:"network-cup",title:"网络航线杯",story:"核对模拟站点并取得正确资料副本。",skill:"地址、来源与传输方向",courseId:"web-address",mode:"network-bay",steps:[{prompt:"任务要求从学习岛取得地图，完整安全路线是什么？",signals:[s("address","地址栏","学习岛","ready"),s("result","摘要来源","地图馆","ready"),s("copy","设备副本","等待取得","active")],options:[o("verify","核对站点和来源后下载，并检查副本"),o("rush","忽略地址直接点"),o("upload","把本机资料上传")],answerId:"verify",explanation:"去向、来源和结果三处状态共同形成证据链。",evidence:"网络海湾：核对后行动并验证结果",wrongFeedback:"取得资料之前，哪两类信息必须一致？"}]},
{id:"creative-cup",title:"创作表达杯",story:"为固定素材选择清楚且合规的作品结构。",skill:"版式、数据与版权",courseId:"media-copyright",mode:"creative-workshop",steps:[{prompt:"用授权图片和三行数据做一页海报，怎样最清楚？",signals:[s("title","标题","海洋观察","active"),s("data","数据","三类数量"),s("credit","素材署名","需要保留","ready")],options:[o("design","标题分层、数据成表、图片保留署名"),o("crowd","所有内容叠在一起"),o("erase","删除素材来源")],answerId:"design",explanation:"信息层级、合适结构和素材署名共同支持清楚表达。",evidence:"创作工坊：结构选择与来源证据完整",wrongFeedback:"哪个方案同时照顾阅读顺序和素材来源？"}]},
{id:"future-cup",title:"AI 核验杯",story:"把虚构 AI 回答拆成可检查的主张。",skill:"提问、核验与人类决定",courseId:"verify-ai",mode:"future-station",steps:[{prompt:"AI 说“月球每天自己发光”，应怎样处理？",signals:[s("claim","AI 主张","月球自己发光","warning"),s("source","科学资料","月球反射阳光","ready"),s("decision","最终结论","由人判断","active")],options:[o("check","拆出主张，查资料，再由人修正结论"),o("trust","因为是 AI 就照抄"),o("hide","删除不同资料")],answerId:"check",explanation:"工具输出是待核验信息，资料证据和人类判断决定结论。",evidence:"未来协作站：主张经过独立证据核对",wrongFeedback:"哪一步能比较 AI 说法与可靠资料？"}]},
{id:"code-cup",title:"游戏代码杯",story:"修复一个固定得分事件并保持规则公平。",skill:"事件、变量与调试",courseId:"events-handlers",mode:"code-spaceport",steps:[{prompt:"点击星星后分数增加两次，轨迹显示同一事件接了两个处理程序，怎么修？",signals:[s("event","点击事件","触发 1 次","ready"),s("handlers","处理程序","加分 A、加分 B","warning"),s("score","分数","增加 2","active")],options:[o("one","保留一个加分处理程序并复测"),o("more","再接第三个处理程序"),o("reset","每次点击清空分数")],answerId:"one",explanation:"事件只需一个对应加分动作，固定输入复测可确认修复。",evidence:"代码星港：事件轨迹定位重复处理",wrongFeedback:"分数为什么会与处理程序数量一起增加？"}]},
{id:"structure-cup",title:"结构调度杯",story:"为模拟任务选择能表达关系的数据结构。",skill:"栈、队列、树与图",courseId:"graph-routes",mode:"data-structures",steps:[{prompt:"站点之间可双向连接且可能成环，哪种结构最合适？",signals:[s("nodes","站点","A、B、C"),s("edges","连接","A-B、B-C、C-A","active"),s("cycle","关系","存在环")],options:[o("graph","使用图的节点和边"),o("stack","只用后进先出栈"),o("array","只按一个固定索引排队")],answerId:"graph",explanation:"图能直接表示多对多连接和环。",evidence:"数据结构岛：关系形状决定结构选择",wrongFeedback:"哪个结构允许一个节点连接多个节点并回到起点？"}]},
{id:"algorithm-cup",title:"算法策略杯",story:"依据输入特征选择更合适的查找方法。",skill:"正确性与效率",courseId:"algorithm-efficiency",mode:"algorithm-arena",steps:[{prompt:"有序的 64 张编号卡要找 53，哪种策略能利用有序证据？",signals:[s("size","卡片数量","64"),s("order","排列状态","从小到大","ready"),s("target","目标","53","active")],options:[o("binary","从中间比较并每次排除一半"),o("random","随机翻卡"),o("shuffle","先打乱再从头找")],answerId:"binary",explanation:"有序输入允许二分搜索持续缩小一半范围。",evidence:"算法岛：输入特征支持方法选择",wrongFeedback:"哪种方法真正利用了“从小到大”？"}]},
{id:"os-cup",title:"操作系统杯",story:"用资源状态解释模拟任务为什么等待。",skill:"进程、内存与设备队列",courseId:"program-process",mode:"os-control-tower",steps:[{prompt:"进程在内存中、CPU 空闲，但打印队列前有两项，它为何没完成？",signals:[s("process","进程","等待设备","active"),s("cpu","CPU","空闲","ready"),s("device","打印队列","前方 2 项","warning")],options:[o("wait","它在等待设备队列，不是缺内存"),o("gone","进程已经消失"),o("cpu","CPU 必须一直满载")],answerId:"wait",explanation:"多个组件状态共同指出瓶颈在设备队列。",evidence:"操作系统峡谷：跨组件状态解释等待",wrongFeedback:"哪一个资源仍有明确的排队证据？"}]},
{id:"depth-cup",title:"系统深海杯",story:"同时处理模拟路线故障与分组缺失。",skill:"路由与可靠恢复",courseId:"reliable-transfer",mode:"systems-network-depths",steps:[{prompt:"低代价路线故障，分组 1、3 已到而 2 缺失，应怎样恢复？",signals:[s("route","原路线","故障","warning"),s("backup","备用路线","可用且代价 5","ready"),s("packets","编号","1、3 已到","active")],options:[o("repair","改走备用路线，只重传分组 2"),o("broken","继续故障路线"),o("all","重复所有已到分组")],answerId:"repair",explanation:"路线状态决定改路，编号缺口决定精确重传。",evidence:"系统深海：两类证据驱动两个对应动作",wrongFeedback:"分别为路线故障和编号缺口选择最小修复。"}]}
];
