export interface CapstoneTask { id: string; domain: "files" | "keyboard" | "input" | "sequence" | "loop" | "condition" | "debug" | "safety"; title: string; prompt: string; options: Array<{ id: string; label: string }>; correctOption: string; explanation: string; }
export const CAPSTONE_TASKS: CapstoneTask[] = [
  { id: "find-map", domain: "files", title: "找到航线图", prompt: "航线图住在 学习资料/地图/航线.png，应该先打开什么？", options: [{ id: "folder", label: "学习资料文件夹" }, { id: "browser", label: "陌生下载弹窗" }], correctOption: "folder", explanation: "文件夹像住处，沿路径逐层进入就能找到文件。" },
  { id: "keyboard-launch", domain: "keyboard", title: "启动控制台", prompt: "要让焦点按钮执行行动，使用哪个键？", options: [{ id: "space", label: "空格键或回车键" }, { id: "escape", label: "只按 Esc" }], correctOption: "space", explanation: "键盘焦点停在按钮上时，空格或回车可以激活它。" },
  { id: "type-code", domain: "input", title: "输入通信码", prompt: "BIBIX 多了一个 X，先用什么修正？", options: [{ id: "backspace", label: "退格键 Backspace" }, { id: "caps", label: "大写锁定 Caps Lock" }], correctOption: "backspace", explanation: "退格键删除光标前的字符。" },
  { id: "order-bridge", domain: "sequence", title: "修复能量桥", prompt: "哪组顺序能安全完成任务？", options: [{ id: "correct-order", label: "拿工具 → 修桥 → 返回" }, { id: "wrong-order", label: "修桥 → 返回 → 拿工具" }], correctOption: "correct-order", explanation: "电脑从上到下执行，前一步要准备后一步需要的条件。" },
  { id: "loop-lights", domain: "loop", title: "点亮四角灯", prompt: "相同动作要做四遍，哪种程序更清楚？", options: [{ id: "repeat", label: "重复 4 次：前进、点灯" }, { id: "single", label: "只执行 1 次" }], correctOption: "repeat", explanation: "固定次数循环能简洁表达重复动作。" },
  { id: "condition-gate", domain: "condition", title: "通过安全门", prompt: "如果绿灯亮就前进，否则应该怎样？", options: [{ id: "wait", label: "等待并重新观察" }, { id: "always-go", label: "不看信号直接前进" }], correctOption: "wait", explanation: "条件为假时执行否则分支。" },
  { id: "debug-beacon", domain: "debug", title: "修复信标程序", prompt: "期望闪 4 次，实际闪 3 次，先改哪里？", options: [{ id: "count", label: "把重复次数 3 改成 4" }, { id: "rewrite", label: "把所有程序全部删除" }], correctOption: "count", explanation: "实际比期望少一次，先做与证据吻合的最小修改。" },
  { id: "safety-message", domain: "safety", title: "处理陌生请求", prompt: "弹窗催你发送家庭住址领奖，应该怎么做？", options: [{ id: "close-ask", label: "不发送，关闭并告诉大人" }, { id: "send", label: "马上发送" }], correctOption: "close-ask", explanation: "住址是私密信息，催促领奖也是警告线索。" },
];
export interface CapstoneState { completedTaskIds: string[]; wrongAttempts: number; feedback: string; complete: boolean; }
export const INITIAL_CAPSTONE_STATE: CapstoneState = { completedTaskIds: [], wrongAttempts: 0, feedback: "从第一座能量塔开始。", complete: false };
export function answerCapstoneTask(state: CapstoneState, taskId: string, optionId: string): CapstoneState { if (state.complete || state.completedTaskIds.includes(taskId)) return state; const task = CAPSTONE_TASKS.find((item) => item.id === taskId); if (!task || optionId !== task.correctOption) return { ...state, wrongAttempts: state.wrongAttempts + 1, feedback: "能量还在。回想对应课程的规则，再试一次。" }; const completedTaskIds = [...state.completedTaskIds, task.id]; return { ...state, completedTaskIds, feedback: task.explanation, complete: completedTaskIds.length === CAPSTONE_TASKS.length }; }
