import { useState } from "react";
import { searchItems, sortItems, type BackpackAction, type BackpackState } from "@/lib/learning-backpack-lesson";
interface Props { state: BackpackState; onAction: (action: BackpackAction) => void; onSearch?: (query: string) => void; onSort?: () => void; }
const FOLDERS = ["数学", "科学", "语文", "图片", "我的作品"];
export function BackpackOrganizer({ state, onAction, onSearch, onSort }: Props) {
  const [selected, setSelected] = useState<string | null>(null); const [query, setQuery] = useState(""); const [sorted, setSorted] = useState(false); const [renameValue, setRenameValue] = useState("");
  const visible = query ? searchItems(state.items, query) : state.items.filter((item) => !item.trashed); const shown = sorted ? sortItems(visible, "name") : visible; const trash = state.items.filter((item) => item.trashed);
  return <div className="backpack-organizer"><div className="organizer-tools"><label>搜索文件<input onChange={(event) => { setQuery(event.target.value); onSearch?.(event.target.value); }} placeholder="输入数学试试" value={query}/></label><button onClick={() => { setSorted(true); onSort?.(); }} type="button">按名称排序</button><span role="status">{state.feedback}</span></div><div className="organizer-files">{shown.map((item) => <button aria-pressed={selected === item.id} key={item.id} onClick={() => { setSelected(item.id); setRenameValue(item.name); }} type="button">📄 {item.name}<small>{item.folder}</small></button>)}</div><div className="organizer-actions"><fieldset><legend>移动所选文件到</legend>{FOLDERS.map((folder) => <button disabled={!selected} key={folder} onClick={() => selected && onAction({ type: "move", itemId: selected, folder })} type="button">{folder}</button>)}</fieldset><label>修改名称<input disabled={!selected} onChange={(event) => setRenameValue(event.target.value)} value={renameValue}/></label><button disabled={!selected} onClick={() => selected && onAction({ type: "rename", itemId: selected, name: renameValue })} type="button">确认重命名</button><button disabled={!selected} onClick={() => selected && onAction({ type: "trash", itemId: selected })} type="button">放入回收站</button></div><section className="virtual-trash"><h3>回收站</h3>{trash.length ? trash.map((item) => <button key={item.id} onClick={() => onAction({ type: "restore", itemId: item.id })} type="button">恢复 {item.name}</button>) : <p>回收站是空的</p>}</section></div>;
}
