import { useState } from "react";
import { runSafetyProgram, type SafetyInputs } from "@/lib/rainy-condition-lesson";
import { isRepeatedPointerActivation } from "@/lib/interaction-guard";
const SCENARIOS: SafetyInputs[] = [{ raining: true, bridgeOpen: false }, { raining: false, bridgeOpen: true }, { raining: true, bridgeOpen: true }];
interface Props { onComplete: () => void; }
export function ConditionLab({ onComplete }: Props) {
  const [index, setIndex] = useState(0); const [equipment, setEquipment] = useState<string | null>(null); const [bridgeAction, setBridgeAction] = useState<string | null>(null); const [feedback, setFeedback] = useState("观察条件，再选择两个分支结果。"); const scenario = SCENARIOS[index]; const expected = runSafetyProgram(scenario);
  function check(detail: number) { if (isRepeatedPointerActivation(detail)) return; if (equipment === expected.equipment && bridgeAction === expected.bridgeAction) { if (index === SCENARIOS.length - 1) onComplete(); else { setIndex((value) => value + 1); setEquipment(null); setBridgeAction(null); setFeedback("条件改变了，请重新运行同一段程序。"); } } else setFeedback("程序给了新证据。逐个检查：下雨吗？桥开放吗？"); }
  return <div className="condition-lab"><div className="condition-weather"><span>{scenario.raining ? "🌧️" : "☀️"}</span><strong>{scenario.raining ? "正在下雨：真" : "正在下雨：假"}</strong><span>{scenario.bridgeOpen ? "🟢" : "🔴"}</span><strong>{scenario.bridgeOpen ? "桥开放：真" : "桥开放：假"}</strong></div><div className="condition-program"><section><code>如果 正在下雨</code><button aria-pressed={equipment === "umbrella"} onClick={() => setEquipment("umbrella")} type="button">那么：撑伞 ☂️</button><button aria-pressed={equipment === "sunhat"} onClick={() => setEquipment("sunhat")} type="button">否则：戴遮阳帽 🧢</button></section><section><code>如果 桥开放</code><button aria-pressed={bridgeAction === "cross"} onClick={() => setBridgeAction("cross")} type="button">那么：过桥</button><button aria-pressed={bridgeAction === "wait"} onClick={() => setBridgeAction("wait")} type="button">否则：等待</button></section></div><p role="status">{feedback} 场景 {index + 1}/3</p><button className="primary-action" onClick={(event) => check(event.detail)} type="button">运行条件程序</button></div>;
}
